<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit page</title>
</head>
<body>
<h2>Create user page</h2>
<form action="<? $_REQUEST['uri'] ?>" method="post" enctype="multipart/form-data">
    Name: <input type="text" name="login" required><br>
    Password: <input type="text" name="password" required><br>
    Email: <input type="email" name="email" required><br>
    Age: <input type="text" name="age" required><br>
    Description: <textarea name="description"></textarea><br>
    Photo: <input type="file" name="photo"><br>
    <input type="submit" value="Create">
</form>
</body>
</html>