<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login page</title>
</head>
<body>
<h2>Login page</h2><br>
<form action="/login" method="post">
    Login: <input type="text" name="login"><br>
    Password: <input type="text" name="password"><br>
    <input type="submit" value="Login"><br>
</form>
</body>
</html>